<source>
  @type tail
  path /https://grafana.com/orgs/azadehsaamani
  tag your_application_logs
  format json
</source>
<match your_application_logs>
  @type prometheus
  <labels>
    severity ${record['severity']}
   </labels>
</match>
scrape_configs:
  - job_name: 'fluentd'
    static_configs:
      - targets: ['localhost:32000'] 
